name: Size

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
